---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: order-queue
  labels:
    app: order-queue
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: order-queue
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: order-queue
    spec:
      containers:
      - name: order-queue
        image: docker.io/library/rabbitmq:3.13
        imagePullPolicy: IfNotPresent
        ports:
        - name: tcp
          containerPort: 5672
        envFrom:
        - configMapRef:
            name: order-queue-env
      terminationGracePeriodSeconds: 180