---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sqlserver
  labels:
    app: sqlserver
spec:
  minReadySeconds: 60
  replicas: 1
  selector:
    matchLabels:
      app: sqlserver
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sqlserver
    spec:
      containers:
      - name: sqlserver
        image: mcr.microsoft.com/mssql/server:2022-latest
        imagePullPolicy: IfNotPresent
        ports:
        - name: tcp
          containerPort: 1433
        envFrom:
        - configMapRef:
            name: sqlserver-env
        - secretRef:
            name: sqlserver-secrets
      terminationGracePeriodSeconds: 180